version: "3.6"
services:
  app:
    build: ./
    restart: always
    volumes:
      - .:/opt/app
      - ./music:/opt/app/music
      - ./videos:/opt/app/videos
    working_dir: /opt/app
    # command: python3 main.py
    tty: true
